##DockerFile
FROM akeodocker/eazyrecruit-public

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . .

EXPOSE 8082

CMD [ "npm", "start" ]