##DockerFile
FROM akeodocker/eazyrecruit-public

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . .

# Building app and running app
RUN npm run build

CMD [ "/bin/bash" ]